import { Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { categorySales, products, salesWeek } from "@/lib/pos-data";
import { PageHeader } from "./app-shell";
import { ProductImage, SectionCard, StatsRow, StockBadge, money } from "./pos-ui";
import { usePos } from "./pos-context";

const chartColors=["var(--chart-1)","var(--chart-2)","var(--chart-3)","var(--chart-4)","var(--chart-5)","var(--chart-6)"];
export function DashboardScreen(){const {t}=usePos();return <>
 <PageHeader title={t("dashboard")} subtitle="Jueves, 10 de septiembre · Resumen de actividad"/>
 <StatsRow/>
 <div className="mt-4 grid grid-cols-[1.6fr_1fr] gap-4">
  <SectionCard title="Ventas de los últimos 7 días" subtitle="Ingresos brutos diarios"><div className="h-[230px]"><ResponsiveContainer width="100%" height="100%"><LineChart data={salesWeek} margin={{top:10,right:8,left:-20,bottom:0}}><XAxis dataKey="d" axisLine={false} tickLine={false} tick={{fontSize:11,fill:"var(--muted-foreground)"}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:11,fill:"var(--muted-foreground)"}}/><Tooltip contentStyle={{borderRadius:6,border:"1px solid var(--border)",background:"var(--popover)",fontSize:12}}/><Line type="monotone" dataKey="v" stroke="var(--primary)" strokeWidth={2.5} dot={{r:3,fill:"var(--primary)",strokeWidth:0}} activeDot={{r:5}} isAnimationActive={false}/></LineChart></ResponsiveContainer></div></SectionCard>
  <SectionCard title="Ventas por categoría" subtitle="Distribución del mes"><div className="flex h-[230px] items-center"><div className="h-full flex-1"><ResponsiveContainer><PieChart><Pie data={categorySales} dataKey="value" innerRadius={54} outerRadius={78} paddingAngle={3} stroke="none" isAnimationActive={false}>{categorySales.map((_,i)=><Cell key={i} fill={chartColors[i]}/>)}</Pie><Tooltip contentStyle={{borderRadius:6,border:"1px solid var(--border)",background:"var(--popover)",fontSize:12}}/></PieChart></ResponsiveContainer></div><div className="w-32 space-y-2">{categorySales.map((x,i)=><div key={x.name} className="flex items-center justify-between text-[11px]"><span className="flex items-center gap-2"><i className="size-2 rounded-full" style={{background:chartColors[i]}}/>{x.name}</span><b>{x.value}%</b></div>)}</div></div></SectionCard>
 </div>
 <div className="mt-4 grid grid-cols-2 gap-4">
  <SectionCard title="Productos más vendidos" subtitle="Últimos 30 días"><div className="space-y-1">{products.slice(0,4).map((p,i)=><div key={p.id} className="flex items-center gap-3 border-b py-2.5 last:border-0"><span className="w-4 text-xs font-semibold text-muted-foreground">{i+1}</span><ProductImage product={p} size="sm"/><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{p.name}</p><p className="text-[10px] text-muted-foreground">{p.category}</p></div><div className="text-right"><p className="text-xs font-semibold">{84-i*13} uds.</p><p className="text-[10px] text-success">{money((p.price-p.cost)*(84-i*13))}</p></div></div>)}</div></SectionCard>
  <SectionCard title="Productos con poco stock" subtitle="Requieren atención"><div className="space-y-1">{products.filter(p=>p.state!=="ok").map(p=><div key={p.id} className="flex items-center gap-3 border-b py-2.5 last:border-0"><ProductImage product={p} size="sm"/><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{p.name}</p><p className="text-[10px] text-muted-foreground">Mínimo: {p.min} uds.</p></div><strong className="text-xs">{p.stock}</strong><StockBadge state={p.state}/></div>)}</div></SectionCard>
 </div>
 </>}