import { ArrowDown, ArrowUp, Boxes, CircleDollarSign, Clock3, PackageOpen, SlidersHorizontal } from "lucide-react";
import { useState } from "react";
import { products } from "@/lib/pos-data";
import { PageHeader } from "./app-shell";
import { ProductImage, StockBadge, money } from "./pos-ui";
import { usePos } from "./pos-context";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const stat=[{l:"Stock total",v:"248 uds.",i:Boxes},{l:"Entradas (mes)",v:"126",i:ArrowDown},{l:"Salidas (mes)",v:"312",i:ArrowUp},{l:"Valor del inventario",v:"3.842,60 €",i:CircleDollarSign}];
const moves=[{time:"11:06",name:"Inca Kola 300 ml",type:"Salida",qty:"−2",employee:"Laura M.",reason:"Venta #V-10482"},{time:"10:42",name:"Harina PAN blanca 1 kg",type:"Entrada",qty:"+24",employee:"Carlos R.",reason:"Compra #C-302"},{time:"10:18",name:"Yuca congelada 1 kg",type:"Ajuste",qty:"−3",employee:"Josias E.",reason:"Merma"},{time:"09:51",name:"Chifles salados 150 g",type:"Salida",qty:"−1",employee:"Laura M.",reason:"Venta #V-10479"}];
export function InventoryScreen(){const {t}=usePos();const [filter,setFilter]=useState("all");const visible=filter==="all"?products:products.filter(p=>p.state===filter);const filters=[{id:"all",label:t("all")},{id:"low",label:t("low")},{id:"critical",label:t("critical")},{id:"out",label:t("out")}];return <><PageHeader title={t("stock")} subtitle="Control y trazabilidad del inventario" action={<Button><SlidersHorizontal/>Registrar ajuste</Button>}/><Tabs defaultValue="inventory"><TabsList><TabsTrigger value="inventory">{t("inventory")}</TabsTrigger><TabsTrigger value="moves">{t("movements")}</TabsTrigger></TabsList><TabsContent value="inventory" className="mt-4"><div className="grid grid-cols-4 gap-4">{stat.map(x=><div key={x.l} className="flex items-center gap-4 rounded-lg border bg-card p-4"><div className="grid size-10 place-items-center rounded-md bg-primary/10 text-primary"><x.i size={19}/></div><div><p className="text-[11px] text-muted-foreground">{x.l}</p><p className="text-lg font-bold">{x.v}</p></div></div>)}</div><div className="my-4 flex gap-2">{filters.map(x=><Button key={x.id} variant={filter===x.id?"default":"outline"} size="sm" onClick={()=>setFilter(x.id)}>{x.label}</Button>)}</div><div className="overflow-hidden rounded-lg border bg-card"><table className="w-full text-left text-xs"><thead className="border-b bg-muted/50 text-[10px] uppercase text-muted-foreground"><tr>{["Producto","Stock actual","Stock mínimo","Último movimiento","Ubicación","Estado"].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{visible.map((p,i)=><tr key={p.id} className="border-b last:border-0"><td className="px-4 py-2"><div className="flex items-center gap-3"><ProductImage product={p} size="sm"/><b>{p.name}</b></div></td><td className="px-4 font-bold">{p.stock}</td><td className="px-4 text-muted-foreground">{p.min}</td><td className="px-4">Hoy, {11-i}:2{i}</td><td className="px-4">A-{String(i+1).padStart(2,"0")}</td><td className="px-4"><StockBadge state={p.state}/></td></tr>)}</tbody></table></div></TabsContent><TabsContent value="moves" className="mt-5"><div className="rounded-lg border bg-card p-6"><h2 className="mb-6 text-sm font-semibold">Movimientos de hoy</h2><div className="relative ml-3 border-l pl-7">{moves.map((m,i)=><div key={i} className="relative pb-7 last:pb-0"><span className={`absolute -left-[35px] top-0 grid size-4 place-items-center rounded-full ${m.type==="Entrada"?"bg-success":m.type==="Salida"?"bg-destructive":"bg-info"}`}/><div className="grid grid-cols-[70px_1fr_100px_80px_130px_160px] items-center"><span className="flex items-center gap-1 text-[11px] text-muted-foreground"><Clock3 size={12}/>{m.time}</span><b className="text-xs">{m.name}</b><span className="text-xs">{m.type}</span><b className="text-xs">{m.qty}</b><span className="text-xs">{m.employee}</span><span className="text-xs text-muted-foreground">{m.reason}</span></div></div>)}</div></div></TabsContent></Tabs></>}