import { AlertTriangle, ArrowDownRight, ArrowUpRight, Package, TrendingUp, WalletCards } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { Product, StockState } from "@/lib/pos-data";

export const money=(n:number)=>new Intl.NumberFormat("es-ES",{style:"currency",currency:"EUR"}).format(n);
export function ProductImage({product,size="md"}:{product:Product;size?:"sm"|"md"|"lg"}){const classes=size==="sm"?"size-10":size==="lg"?"h-44 w-full":"size-12";return <img src={product.image} alt={product.name} loading="lazy" width={768} height={768} className={`${classes} shrink-0 rounded-md bg-muted object-cover`}/>}
export function StockBadge({state}:{state:StockState}){const map={ok:["Correcto","bg-success/12 text-success"],low:["Bajo","bg-warning/12 text-warning"],critical:["Crítico","bg-destructive/12 text-destructive"],out:["Sin stock","bg-muted text-muted-foreground"]} as const;return <Badge variant="secondary" className={`border-0 ${map[state][1]}`}>{map[state][0]}</Badge>}
const stats=[{label:"Ventas del día",value:"482,35 €",trend:"+12%",note:"respecto ayer",icon:WalletCards,tone:"primary"},{label:"Beneficio del día",value:"164,90 €",trend:"+8,4%",note:"margen 34,2%",icon:TrendingUp,tone:"success"},{label:"Productos en stock",value:"248",trend:"+6",note:"esta semana",icon:Package,tone:"info"},{label:"Stock crítico",value:"12",trend:"-3",note:"productos",icon:AlertTriangle,tone:"warning"}] as const;
export function StatsRow(){return <div className="grid grid-cols-4 gap-4">{stats.map((s,i)=><Card key={s.label} className="group transition-all duration-150 hover:-translate-y-0.5 hover:shadow-md"><CardContent className="flex items-start justify-between p-5"><div><p className="text-xs font-medium text-muted-foreground">{s.label}</p><p className="mt-2 text-[25px] font-bold tracking-normal">{s.value}</p><div className="mt-2 flex items-center gap-1.5 text-[11px]"><span className={i===3?"text-destructive":"text-success"}>{s.trend}</span><span className="text-muted-foreground">{s.note}</span></div></div><div className={`grid size-10 place-items-center rounded-lg bg-${s.tone}/10 text-${s.tone}`}><s.icon size={19}/></div></CardContent></Card>)}</div>}
export function SectionCard({title,subtitle,children,className=""}:{title:string;subtitle?:string;children:React.ReactNode;className?:string}){return <Card className={className}><CardHeader className="flex-row items-center justify-between space-y-0 pb-3"><div><CardTitle className="text-sm">{title}</CardTitle>{subtitle&&<p className="mt-1 text-[11px] text-muted-foreground">{subtitle}</p>}</div></CardHeader><CardContent>{children}</CardContent></Card>}
export function Delta({positive=true,children}:{positive?:boolean;children:React.ReactNode}){const I=positive?ArrowUpRight:ArrowDownRight;return <span className={positive?"inline-flex items-center text-success":"inline-flex items-center text-destructive"}><I size={13}/>{children}</span>}