import { Banknote, Barcode, CreditCard, Minus, Plus, Search, Trash2, XCircle } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { products } from "@/lib/pos-data";
import { ProductImage, money } from "./pos-ui";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type CartItem={id:number;qty:number};
export function PosScreen(){const [cart,setCart]=useState<CartItem[]>([{id:1,qty:2},{id:3,qty:1},{id:7,qty:1}]);const [query,setQuery]=useState("");
 const change=(id:number,delta:number)=>setCart(c=>c.map(x=>x.id===id?{...x,qty:Math.max(1,x.qty+delta)}:x)); const subtotal=cart.reduce((a,x)=>a+(products.find(p=>p.id===x.id)?.price??0)*x.qty,0);const iva=subtotal-subtotal/1.1;
 const addFirst=()=>{const p=products.find(p=>p.name.toLowerCase().includes(query.toLowerCase())||p.barcode.includes(query));if(!p){toast.error("Producto no encontrado");return;}setCart(c=>c.some(x=>x.id===p.id)?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{id:p.id,qty:1}]);setQuery("")};
 return <div className="grid min-h-[calc(100dvh-120px)] grid-cols-[minmax(0,7fr)_minmax(320px,3fr)] gap-5">
  <section className="flex min-w-0 flex-col"><div><h1 className="text-[25px] font-bold">TPV Venta</h1><p className="mt-1 text-[13px] text-muted-foreground">Ticket abierto · Caja 01</p></div>
   <div className="relative mt-5"><Barcode className="absolute left-4 top-1/2 -translate-y-1/2 text-primary" size={23}/><Input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addFirst()} className="h-14 bg-card pl-12 pr-24 text-sm shadow-sm" placeholder="Escanee un código de barras o escriba un producto..."/><Button className="absolute right-2 top-2 h-10" onClick={addFirst}><Search/>Buscar</Button></div>
   <div className="mt-4 overflow-hidden rounded-lg border bg-card"><div className="grid grid-cols-[minmax(240px,1fr)_90px_130px_90px_44px] border-b bg-muted/50 px-4 py-2.5 text-[10px] font-semibold uppercase text-muted-foreground"><span>Producto</span><span>Precio</span><span>Cantidad</span><span>Subtotal</span><span/></div>{cart.map(item=>{const p=products.find(x=>x.id===item.id);if(!p)return null;return <div key={item.id} className="grid grid-cols-[minmax(240px,1fr)_90px_130px_90px_44px] items-center border-b px-4 py-3 last:border-0"><div className="flex items-center gap-3"><ProductImage product={p}/><div><p className="text-xs font-semibold">{p.name}</p><p className="text-[10px] text-muted-foreground">{p.category} · {p.sku}</p></div></div><span className="text-xs font-medium">{money(p.price)}</span><div className="flex items-center"><Button size="icon" variant="outline" className="size-8" onClick={()=>change(p.id,-1)}><Minus/></Button><span className="w-9 text-center text-xs font-bold">{item.qty}</span><Button size="icon" variant="outline" className="size-8" onClick={()=>change(p.id,1)}><Plus/></Button></div><strong className="text-xs">{money(p.price*item.qty)}</strong><Button size="icon" variant="ghost" className="text-muted-foreground hover:text-destructive" onClick={()=>setCart(c=>c.filter(x=>x.id!==p.id))}><Trash2/></Button></div>})}</div>
  </section>
  <aside className="flex flex-col rounded-lg border bg-card p-5 shadow-sm"><h2 className="text-base font-bold">Resumen del pedido</h2><p className="mt-1 text-xs text-muted-foreground">{cart.reduce((a,x)=>a+x.qty,0)} artículos</p><div className="my-6 space-y-3 border-y py-5 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Subtotal</span><b>{money(subtotal-iva)}</b></div><div className="flex justify-between"><span className="text-muted-foreground">IVA incluido</span><b>{money(iva)}</b></div><div className="flex justify-between"><span className="text-muted-foreground">Descuento</span><button className="text-xs font-semibold text-primary">Añadir</button></div></div><div className="flex items-end justify-between"><span className="text-sm font-bold">TOTAL</span><strong className="text-[32px] leading-none">{money(subtotal)}</strong></div><div className="mt-auto space-y-3 pt-8"><Button className="h-14 w-full text-sm" onClick={()=>toast.success("Cobro en efectivo preparado")}><Banknote/>Cobrar en efectivo</Button><Button variant="outline" className="h-14 w-full text-sm" onClick={()=>toast.success("Terminal de tarjeta preparado")}><CreditCard/>Cobrar con tarjeta</Button><Button variant="ghost" className="h-11 w-full text-muted-foreground" onClick={()=>setCart([])}><XCircle/>Cancelar venta</Button></div></aside>
 </div>}